name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: papier.o2switch.net
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          remote-dir: /public_html/Legourmand/Legourmand/
