name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape pour téléverser le répertoire 'public' à la racine du site
      - name: Upload 'public' directory to /public_html/Legourmand2/
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: papier.o2switch.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: 'ftp'
          local-dir: './public/'
          server-dir: '/public_html/Legourmand2/'

