name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files to /public_html/Legourmand/
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: papier.o2switch.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: 'ftp'
          local-dir: './public/'
          server-dir: '/public_html/Legourmand/'

      # Étape pour les fichiers à envoyer dans /public_html/Legourmand/Legourmand/
      - name: Upload files to /public_html/Legourmand/Legourmand/
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: papier.o2switch.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: 'ftp'
          local-dir: ./
          server-dir: /public_html/Legourmand/Legourmand/
          exclude: 'public/*, node_modules/**, vendor/**, storage/**'
