name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: papier.o2switch.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: 'ftp'  # Spécifiez 'ftp' ou 'sftp' selon votre configuration
          local-dir: ./
          server-dir: /public_html/Legourmand/Legourmand/
